---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.1.60"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "S@!b@b@1985"
    datacenter_name: "pvihome"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: newserver
      template: CentOS_Base
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      datastore: "iscsi-datastore01"
      networks:
      - name: VM Network
        type: dhcp
      customization:
        hostname: "local"
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
