---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.1.1.60"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "S@!b@b@1985"
    datacenter_name: "pvihome"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: newserver
      template: CentOS_Base
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      datastore: "iscsi-datastore01"
      networks:
      - name: VM Network
        ip: 192.168.1.35
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        type: static
        dns_servers: 192.168.1.23
      customization:
        hostname: "local"
        dns_servers:
        - 192.168.1.23
        - 192.168.1.1
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost